name = "SquareIsingModel"
uuid = "723ee7ca-8220-4cb6-9f2e-031e2886e2e7"
authors = "Jorge Fernandez-de-Cossio-Diaz <j.cossio.diaz@gmail.com>"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"
